Actividad 1
Crea un programa que solicite al usuario ingresar 9 valores. Los valores ingresados deben ser almacenados en un único arreglo bidimensional (matriz).y debe mostrarlos posteriormente por pantalla. Sigue estos pasos:
1. Declara el tipo de dato que almacenará la matriz.
2. Define la dimensión del arreglo, en este caso, 3X3 (ya que precisamos almacenar 9 datos).
3. Utiliza un bucle para recorrer el arreglo recién creado, posición por posición, y solicita 
al usuario que introduzca un dato. Puedes emplear una estructura de bucle "Para" para esta tarea.  
Recuerda que necesitarás bucles anidados para recorrer cada fila y cada columna, 
siendo el bucle externo para las filas y el interno para las columnas.

una matriz en python es una lista de listas  
en este ejmplo 3x3
```python
[
    [0 1 2] # fila 0 con 3 columnas
    [0 1 2] # fila 1 con 3 columnas
    [0 1 2] # fila 2 con 3 columnas
]
```
Hasta alli todo igual que antes este primer ejercicio lo vamos a resolver como se parece a pseint  
pero en python hay librerias para manejar vectores (arreglos unidimensionales) y matrices(arreglos n dimensionales)  
una y la principal que toma la lógica del cálculo de matrices es **numpy**... de alli se ha ampliado a librerias como  
**pandas** dedicada al manejo de las dos dimensiones (es decir la tablas) no nos vamos a quemar el coco aprendiendo estas librerias  
no es la idea pero si haremos uso de ellas para resolver estos ejercicios pero con el poder de python  
Puedes si quieres construir los sistemas como los desarrollaste en pseint para practicar esta bien  
pero el mundo python es una perdida de tiempo... lo mejor es pythonizar el codigo simplicar la vida pues 

In [4]:
# para crear una matriz usaramos la list comprehensions 
# solo basta anidar una list dendtro de otra por ejemplo para crear las columnas
# columnas = [rn.randint(0,100) for _ in range(3)] # te fijas que 3 en range son por las columnas 
# para crear las filas ahora habria que rellenar con las columnas anteriores algo como 
# filas = [columnas[i] for i in range(3)]
# pero se puede hacer en una sola linea

import random as rn
matriz = [[rn.randint(0,100) for _ in range(3)] for _ in range(3)]
print(*matriz,sep='\n')

# si quereremos que el usuario introduzca los numeros
# matriz = [[int(input('Introduce un numero')) for _ in range(3)] for _ in range(3)]
# si queremos que sean numeros reales
# matriz = [[rn.uniform(0,100) for _ in range(3)] for _ in range(3)]
# recuerda que tambien puedes imprimirlo asi
# for fila in matriz:
#     print(fila)

[10, 7, 49]
[94, 77, 74]
[58, 64, 15]


In [6]:
# como lo hace numpy
import numpy as np
matriz_np = np.random.randint(0,100, size=(3,3)) 
print(matriz_np)  # ya no necesitamos el desempaquetador y fijate que la muestra como esperamos

# las librerias de python trabajan con POO y son clases 
# que luego instancian un objeto por ejemplo np o abajo pa (alias de pandas)
# y ese objeto contiene metodos y atributos que vamos a usar 
# en este caso random.randint probablemente lo tomen de la libreria random
# con el atributo size=(3,3) le indicamos la matriz 3x3

[[42 44  5]
 [92 67  7]
 [ 6 83 59]]


In [10]:
# como lo hace pandas
# puede tomar datos de muchos lados pero ahora solo los tomaremos de numpy
# la estructura de dots en pandas se llama dataframe
import pandas as pd

df = pd.DataFrame(matriz_np)
df # ves el estilacho, y ademas podes ponerle nombre a las columnas como en las tablas pero no sera el caso
# df = pd.DataFrame(matriz, columns=['Col1','Col2','Col3'])


0   1   2
0  42  44   5
1  92  67   7
2   6  83  59

Actividad 2 
Dada una matriz de tamaño n x m, donde n y m son valores 
ingresados por el usuario, se requiere implementar dos subprogramas:
* El primer subprograma se encargará de llenar la matriz con números aleatorios.
* El segundo subprograma calculará y mostrará la suma de todos los elementos de la matriz.
Después de ejecutar ambos subprogramas, se mostrará la matriz 
generada junto con los resultados de la suma por pantalla.

In [20]:
# como en pseint pero con list comprehension
import random as rn
filas = int(input('Introduce un numero de filas (n)'))
columnas = int(input('Introduce un numero de columnas (m)'))
matriz = [[rn.randint(0,100) for _ in range(columnas)] for _ in range(filas)]
print(*matriz,sep='\n')
# para poder aplicar la funcion sum() debemos tener una lista simple
suma_total = sum([number for lista in matriz for number in lista]) # como la list crompehensions recorriendo los numeros 
print(f'La suma de todos los elementos de la matriz {suma_total}')

[71, 28, 87, 28, 71]
[94, 1, 96, 0, 79]
[78, 3, 24, 74, 94]
[45, 31, 37, 25, 13]
La suma de todos los elementos de la matriz 979


In [95]:
# interesante es hacer la funcion suma recursiva
def suma_recursiva(filas,columnas, i, j,matriz):
    if not i:   # recuerda no olvides que cero es falso cuando i vale 0 not i es True
        return 0
    elif not j:
        return suma_recursiva(filas,columnas, i-1,columnas,matriz)  # cambiamos la fila
    else:
        return matriz[i-1][j-1] + suma_recursiva(filas,columnas, i, j-1,matriz) # recorremos las columnas

suma_recursiva(filas,columnas, filas, columnas,matriz)

979

In [26]:
# veamos numpy
import numpy as np
filas = int(input('Introduce un numero de filas (n)'))
columnas = int(input('Introduce un numero de columnas (m)'))
matriz_np = np.random.randint(0,100, size=(filas,columnas)) 
print(matriz_np)
np.sum(matriz_np)

[[22 30 93 28 99]
 [53 11 76 17 63]
 [39 62 66 89 27]
 [75 99 46 53 36]]


1084

In [32]:
# veamos pandas
import pandas as pd
# df = pd.DataFrame(matriz) como habiamos comentado pandas todma datos de muchas partes inclusive de arreglos de tipo py 
df = pd.DataFrame(matriz_np)  # pero como es mas facil desde np los cosntruimos desde alli
display(df) # la funcion display se usa en jupyter notebook para imprimir con el decorado de JS
df.values.sum() # values es un metodo para agrupar los valores (es decir los datos, en un arreglo np) y luego operar matematicamente con el metodo sum y mostrar todo

0   1   2   3   4
0  22  30  93  28  99
1  53  11  76  17  63
2  39  62  66  89  27
3  75  99  46  53  36

1084

Actividad 3
Crea un programa que cumpla con las siguientes condiciones:  
* Define y dimensiona una matriz de 5x5 para almacenar datos numéricos enteros.
* Rellena la matriz de manera aleatoria con números comprendidos entre 10 y 40.
* Permite al usuario ingresar un número para buscarlo dentro de la matriz.
* Si el número se encuentra, muestra en pantalla un mensaje adecuado junto 
con las coordenadas en la matriz (fila y columna). En caso de que el número 
esté repetido, solo se mostrará la posición de la primera ocurrencia.
* Si el número no se encuentra, informa por pantalla.

In [33]:
# en realidad al estar importado arriba ya no hace falta 
# te lo mostramos por costumbre pero no hace falta si ejecutaste una celda anterior 
# una de las ventajas de jupyter notebook es ejecuación celda a celda pero con integraciaon entre
# celdas ejecutadas 
import numpy as np
import pandas as pd  
matriz_np = np.random.randint(10,40, size=(5,5))
df = pd.DataFrame(matriz_np)
display(df) 

0   1   2   3   4
0  18  17  32  10  18
1  34  15  16  16  12
2  13  25  28  31  31
3  23  13  34  37  22
4  11  13  27  23  19

In [118]:
# es en esta parte donde explicaremos como hacer el contexto de busqueda
number_search = int(input('Introduce un numero para buscar en la matriz'))
# en pandas (heredado de np) existe la mascara de boleanos que no es mas
# que como reacciona el dataframe ante el operador logico
# como opera sobre cada valor obtenes la misma matriz n x m pero con puros True/False
# dependiendo del resultado logico de la comparacion respectiva  
# es decir df==number_search es una mascara de boelanos 
# con el metodo .any() se le pregunta si hay True si no tiene atributo axis por defaul es 0
# es decir busca por columna, en cambio axis = 1 busca por las filas
# al aplicarlo dos veces me dira si existe una vez al menos o no devuelve un boleano
df_bolean = df==number_search
if df_bolean.any().any():  # si existe en 
    posicion_fil_col = np.where(df_bolean)   # np.where() extrae las posiciones donde se encuentra
    # como una lista de listas la primera lista son las fila en la primera posicion la primera ocurrencia [0][0] 
    # en la segunda lista son las columnas en la primera posicion la primera ocurrencia [1][0]
    fila, columna = posicion_fil_col[0][0], posicion_fil_col[1][0] # aprovechas el concepto de tupla para asignar ambos valores  
    print(f'El numero {number_search} esta dentro de la matriz (primera ocurrencia) en la fila {fila} y en la columna {columna}')
else:
    print(f'El numero {number_search} no esta dentro de la matriz')

# ves como np y pd se unen constantemente? 

El numero 9 no esta dentro de la matriz


Complementario 1
Se desea crear un programa que realice dos subprocesos:  
* En el primer subproceso se rellenará una matriz cuadrada con números aleatorios, 
excepto en la diagonal principal, la cual estará compuesta por ceros. La dimensión 
de la matriz será elegida por el desarrollador mientras sea cuadrada.  
* En el segundo subproceso se imprimirá la matriz resultante.
Después de ejecutar ambos subprocesos, se mostrará la matriz generada por pantalla. 

In [119]:
# recuerda que nos ahorramos los subprocesos o las funciones 
filas_columnas = int(input('Introduce un numero de filas y columnas (sera cuadrada la matriz)'))
matriz_np = np.random.randint(1,100, size=(filas_columnas,filas_columnas))
np.fill_diagonal(matriz_np,0) # con este metodo rellenamos la diagonal prinicial de una matriz con 0 ambos atributos en ese orden 
df = pd.DataFrame(matriz_np)
display(df) 

0   1   2   3
0   0  76  74  73
1  78   0  39  10
2  48  64   0  76
3  75  40  19   0

Complementario 2
Desarrolla un programa para rellenar una matriz de tamaño 3 x 3 con 
los caracteres de una palabra de longitud 9 proporcionada por el usuario, 
asegurando que la palabra se muestre de manera continua en la matriz.

Primero, se debe validar que la palabra ingresada por el usuario tenga 
exactamente 9 caracteres. Luego, se insertará un carácter en cada posición 
de la matriz. Finalmente, se imprimirá la matriz rellenada por pantalla.

Por ejemplo, si el usuario ingresa la palabra "habilidad", la matriz resultante se vería así:  
X   0	1	2  
0	H	A	B  
1	I	L	I  
2	D	A	D  
Una explicación en forma visual de la resolución se puede ver en  
https:docs.google.com/spreadsheets/d/1XZUC2BzjYaTDcOBipbDeZIlfXTtfCCvNFRDJzELJEUg/edit?gid=1944097503#gid=1944097503&range=B2:J16

In [12]:
# con pandas luego de crear una list comprehension la matriz requerida
# no necesito la funcion, podes practicarla para tu experiencia personal pero no con python
import numpy as np
import pandas as pd

palabra = ''
while len(palabra) != 9:
    palabra = input('Introduce una palabra de 9 letras')

matriz_palabra =  [[palabra[i*3+j] for j in range(3)] for i in range(3) ] 
df = pd.DataFrame(matriz_palabra) # como dijimos antes recuerda que puedo ir directo de un arreglo de py a dataframe de pandas
df  


0  1  2
0  h  a  b
1  i  l  i
2  d  a  d

In [19]:
palabra = ''
while len(palabra) != 9:
    palabra = input('Introduce una palabra de 9 letras')
arreglo_palabra = [letra for letra in palabra]    # igual tenemos que generar el arreglo de cada letra de la palabra
matriz_palabra =  np.array(arreglo_palabra).reshape(3,3) # con reshape(fila, columna) se convierte de  arreglo unidimensional a matriz 
df = pd.DataFrame(matriz_palabra)
df
# en la reconversion de arreglos recordemos que matematicamente todo arreglo unidemensional de 9 elementos (por ejemplo)
# se puede convertir en 3x3 o cualquier relacion que sea como resultante 9 en este caso las otras son 1x9 o 9x1 
# otro ejemplo una matriz 4x4 puede reconvertirse en 1x16, 16x1,8x2,8x2  

0  1  2
0  h  a  b
1  i  l  i
2  d  a  d

Complementario 3
Un ejemplo de una matriz mágica es una matriz cuadrada, donde el número de filas es igual al número de columnas, 
y que tiene la propiedad especial de que la suma de sus filas, columnas y diagonales es igual. Por ejemplo:  
X   0	1	2  
0	2	7	6  
1	9	5	1  
2	4	3	8  
En el ejemplo dado, las sumas siempre dan como resultado 15. Se plantea el problema de construir un algoritmo que 
verifique si una matriz de datos enteros es mágica o no. En caso de serlo, el programa debe escribir la suma total. 
Además, el programa debe validar que los números introducidos estén en el rango de 1 a 9. 
El usuario define el tamaño de la matriz, que no debe exceder un orden de 10.
Una explicación en forma visual de la resolución se puede ver en  
https:docs.google.com/spreadsheets/d/1XZUC2BzjYaTDcOBipbDeZIlfXTtfCCvNFRDJzELJEUg/edit?gid=1514302018#gid=1514302018&range=C2:L15

In [109]:
import numpy as np
import pandas as pd
import random as rn
print('Opciones')
print('(1) tamaño decidido por el usuario ')
print('(2) un 3x3 relleno automatico')
choice = input('Introduce la opcion')
if choice == '1':
    filas_columnas = 0
    while 2>filas_columnas or filas_columnas>10:
        filas_columnas = int(input('Introduce un numero de filas y columnas (sera cuadrada la matriz minimo 2 maximo 10)'))
    matriz_np = np.random.randint(1,9, size=(filas_columnas,filas_columnas))
else:
    lista_numeros = list(range(1,10)) 
    rn.shuffle(lista_numeros)
    matriz_np = np.array(lista_numeros).reshape(3,3)
print('*'*20)
df = pd.DataFrame(matriz_np)
display(df)
print('*'*20)
suma_columnas = df.sum(axis=0) # para las columnas axis = 0 o no se indica
suma_filas = df.sum(axis=1) # recuerdas axis en sum define sumar filas (axis = 1) sino se coloca es 0 por default
df.values.trace()  # suma la diagonal prinicipal
df.values[::-1].trace() 
if df.values.trace() == df.values[::-1].trace():
    if df.values.trace() == df.values[::-1].trace():
        print('Es magica', df.values.sum())
    else:
        print('No es magica, pero las diagonales suman lo mismo')
else:
    print('No es magica')

Opciones
(1) tamaño decidido por el usuario 
(2) un 3x3 relleno automatico
********************


0  1
0  2  6
1  1  5

********************
Es magica 14


adicional el reto del corazon
Construi un corazon con los caracteres como se muestra a continuacion
```python  
6666   9999  
66666 99999  
 666609999  
  6660999   
   66099    
    609     
     0     
```

In [147]:
def cada_linea(ini,top, ini2, top2,i):
    # global fila           # se puede resolver con global fila pero hay que eliminar el return al final 
    fila=[]
    for j in range(11):
        if ini<=j<=top:
            print(6,end='')
            fila.append(6)
        elif j==5 and i>=2:
            print(0,end='')
            fila.append(0)
        elif not (ini2<=j<=top2):
            print(' ',end='')
            fila.append(' ')
        else:
            print(9,end='')
            fila.append(9)
    print()
    return fila

arreglo6ini = [0,*range(0,6)]          # fijate como usamos el desempaquetado de range
arreglo6top = [3,*[4]*6]               # o en este caso donde se desempaqueta luego de sextuplicar el arreglo [4]
arreglo9top = [10,*range(10,4,-1)]
arreglo9ini = [*range(7,5,-1),*range(6,3,-1),4,10]
matriz = []

for i in range(7):
    fila = cada_linea(arreglo6ini[i],arreglo6top[i],arreglo9ini[i],arreglo9top[i],i)
    matriz.append(fila)

df = pd.DataFrame(matriz,columns=['E','L','C','O','R','A','Z','Ó','N','P','Y'])
df

6666   9999
66666 99999
 666609999 
  6660999  
   66099   
    609    
     0     


E  L  C  O  R  A  Z  Ó  N  P  Y
0  6  6  6  6           9  9  9  9
1  6  6  6  6  6     9  9  9  9  9
2     6  6  6  6  0  9  9  9  9   
3        6  6  6  0  9  9  9      
4           6  6  0  9  9         
5              6  0  9            
6                 0